project:
  type: website
  output-dir: _site
  resources: mw_owe_database.csv
  
website:
  title: "OWE database"
  repo-url: https://github.com/economic/owe
  search: false
  navbar:
    background: light
    left:
      - text: Overview
        href: index.qmd
      - text: Explore
        menu: 
          - text: "Subgroup figure"
            href: explore/subgroup_figure.qmd
          - text: "Table of studies"
            href: explore/table.qmd
      - text: Download
        href: download.qmd
      - href: documentation.qmd
      - href: submit.qmd
    right:
      - icon: github
        href: https://github.com/economic/owe
        aria-label: OWE GitHub    
  

format:
  html:
    theme: 
      light: [cosmo, theme.scss]
    css: styles.css
    toc: false

editor: visual

