project:
  type: website
  output-dir: docs
  resources: mw_owe_database.csv, mw_owe_studies.csv, mw_owe_studies.bib
  
website:
  title: "OWE database"
  repo-url: https://github.com/economic/owe
  search: false
  navbar:
    background: light
    left:
      - text: Overview
        href: index.qmd
      - text: Explore
        href: table.qmd
      - text: Download
        href: download.qmd
      - href: documentation.qmd
      - text: What's New
        href: news.qmd
      - text: Submit
        href: submit.qmd
    right:
      - icon: github
        href: https://github.com/economic/owe
        aria-label: OWE GitHub    
  

format:
  html:
    theme: 
      light: [cosmo, theme.scss]
    # css: styles.css
    toc: false

editor: visual

