project:
  type: website
  output-dir: docs
  resources: mw_owe_repository.csv, mw_owe_studies.csv, mw_owe_studies.bib
  
website:
  title: "OWE repository"
  site-url: https://economic.github.io/owe
  repo-url: https://github.com/economic/owe
  search: false
  twitter-card:
    title: "Minimum Wage Own Wage Elasticity Repository"
    description: "Representative estimates from minimum wage studies"
    image: "web_assets/twitter_card.png"
    card-style: "summary_large_image"
  navbar:
    background: light
    left:
      - text: Overview
        href: index.qmd
      - text: Explore
        href: table.qmd
      - text: Download
        href: download.qmd
      - href: documentation.qmd
      - text: Exclusions
        href: other_papers.qmd
      - text: What's New
        href: news.qmd
      - text: Submit
        href: submit.qmd
    right:
      - icon: github
        href: https://github.com/economic/owe
        aria-label: OWE GitHub    
  

format:
  html:
    theme: 
      light: [cosmo, theme.scss]
    # css: styles.css
    toc: false

editor: visual

