---
pagetitle: "Minimum wage own-wage elasticity database"
page-layout: custom
section-divs: false
css: index.css
editor: source
execute:
  echo: false

---

::: {.hero-banner}

::: {.content-block}
# Minimum wage own-wage elasticity database

### A collection of estimates from minimum wage research studies

::: {.hero-buttons}
[Explore](explore/subgroup_figure.html){.btn-action-primary .btn-action .btn .btn-success .btn-lg role="button"}
[Download](download.html){#btn-guide .btn-action .btn .btn-info .btn-lg role="button"}
[Documentation](documentation.html){#btn-guide .btn-action .btn .btn-info .btn-lg role="button"}
::: 

:::
:::

::: {.content-block}
```{r}
#| warning: false

library(tidyverse)
data <- read_csv("mw_owe_database.csv", show_col_types = FALSE) 

study_count <- nrow(data) 
```
  
## Distribution of own-wage elasticities from `r study_count` minimum wage studies
```{r}
#| warning: false
#| out-width: 90%
#| fig-cap: 
#|   - "{{< var citation.full >}}"
library(hrbrthemes)
library(viridis)

binned_data <- data %>% 
  mutate(bin = case_when(
    owe_b < -1.2 ~ -1.4,
    owe_b >= -1.2 & owe_b < -0.8 ~ -1.0,
    owe_b >= -0.8 & owe_b < -0.4 ~ -0.6,
    owe_b >= -0.4 & owe_b <  0.0 ~ -0.2,
    owe_b >=  0.0 & owe_b <  0.4 ~  0.2,
    owe_b >=  0.4 & owe_b <  0.8 ~  0.6,
    owe_b >=  0.8 & owe_b <  1.2 ~  1.0,
    owe_b >=  1.2 ~ 1.4
  )) %>% 
  mutate(group = case_when(
    owe_b < -0.8 ~ 'Large negative',
    owe_b >= -0.8 & owe_b < -0.4 ~ 'Medium negative',
    owe_b >= -0.4 ~ 'Small negative, or positive'
  )) %>% 
  count(group, bin) %>%
  ungroup() %>% 
  mutate(bin = bin * -1) 

median_owe <- data %>% 
  summarize(median(owe_b) * -1) %>% 
  pull()

median_owe_label <- paste("Median OWE =", round(median_owe * -1, 2))

y_axis_breaks <- seq(-14, 14, 4) / 10 * -1
y_axis_labels <- c(
  "More negative than -1.2",
  "-1.2  to -0.8",
  "-0.8  to -0.4",
  "-0.4  to  0.0",
  " 0.0  to  0.4",
  " 0.4  to  0.8",
  " 0.8  to  1.2",
  "More positive than 1.2"
)
colors <- viridis::viridis(4) %>% head(3)
binned_data %>% 
  ggplot(aes(y = bin, x = n, fill = group)) +
  geom_col(orientation = "y") + 
  geom_segment(
    aes(x = 0, xend = 22, y = median_owe, yend = median_owe),
    lineend = "round", linetype = "dashed"
  ) +
  annotate(
    "text", 
    x = 22.5, 
    y = median_owe, 
    label = median_owe_label,
    #color = "grey40",
    hjust = 0,
    size = 3.1
  ) + 
  expand_limits(x = 30) +
  scale_y_continuous(breaks = y_axis_breaks, labels = y_axis_labels) +
  scale_x_continuous(breaks = seq(0, 20, 5), minor_breaks = seq(0, 15, 5) + 2.5) +
  scale_fill_manual(values = colors) +
  labs(
    x = "Number of studies",
    y = NULL
  ) +
  theme_ipsum_rc() +
  theme(
    panel.grid.major.y = element_blank(),
    panel.grid.minor.y = element_blank(),
    legend.title=element_blank(),
    legend.position = c(0.85, 0.8),
    axis.title.x = element_text(hjust = 0.6),
    plot.margin = margin(0,0,0,0)
  )
```

```{ojs}
//| output: false

data = FileAttachment("mw_owe_database.csv").csv({typed: true})

```

```{ojs}
//| fig-cap: "{{< var citation.full >}}"
plot = Plot.plot({
  x: {grid: true},
  color: {legend: true},
  marks: [
    Plot.rectX(data, Plot.binY({x: "count"}, {y: "owe_b"})),
    Plot.ruleX([0])
  ]
})
```
:::