---
title: "Changelog"
editor: source
---
Archived releases of the data, and the code used to generate them, are available on [Github](https://github.com/Economic/owe/releases).

## Version 0.16.0
- Removed Belman Wolfson 2010 due to time series variation only

## Version 0.15.0
- Updated estimate from Wiltshire et al 2024 
- Moved Butcher and Dickinson 2023 to working paper status
- Updated bibliography info for Godøy et al 2024 and Azar et al 2023

## Version 0.14.0
- Added Eriksson and Pytlikova 2004; Huet-Vaughn and Piqueras 2023; Vadean and Allan 2021; van Beezooijen, van den Berge, and Salomons 2024 

## Version 0.13.0
- Added Harasztosi and Linder 2019, Manning and Wilson 2004, vom Berge and Frings 2019
- Updated bibliography for Giupponi Joyce Lindner Waters Wernham Xu 2024

## Version 0.12.0
- Added Rao and Risch 2024
- Updated working paper Jha Neumark Rodridguez-Lopez 2023 to published in 2024

## Version 0.11.0
- Added Manning 2021 and Sabia 2009b
- Updated Vergara 2023

## Version 0.10.0
- Added Neumark and Yen 2023; Belman and Wolfson 2010; and Addison Blackburn Cotti 2015

## Version 0.9.1
- Updated Jha Neumark Rodriguez-Lopez 2024 citation to latest version

## Version 0.9.0
- Corrected standard errors from Wursten and Reich 2023 LE, Hampton and Totty 2023

## Version 0.8.0
- Corrected standard error from Wursten 2021
- Refined journal names

## Version 0.7.1
- Refined working paper bibliographic entries in mw_owe_studies.bib output

## Version 0.7.0
- Added Riley and Bondibene 2017

## Version 0.6.1
- Added teens and restaurants_retail columns to data
- Added owe_magnitude column to data

## Version 0.6.0
- Added "year" column to data
- Used weighted average for elasticities from Reich and Wursten 2023, small business paper.
- Corrected elasticities from Even and Macpherson 2014.

## Version 0.5.0
- Corrected employment elasticity from Dow Godøy Lowenstein Reich 2020
- Added "averaged" and "owe_reported" columns to data

## Version 0.4.0
- Added Brown and Herbst 2023
- Corrected country of Bossler and Gerner 2020

## Version 0.3.0
- Finally added changelog
